name: build-and-deploy

on:
  schedule:
    - cron: '30 21 * * *'   # 毎日 06:30 JST（UTC 21:30）
  workflow_dispatch:         # 手動実行も可

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # RSS → data/index.json / data/ep/*.json
      - name: Build site data
        run: python scripts/build.py

      # ▼ デバッグ（CSVの存在と先頭行をログに出す）
      - name: List CSV in data/
        run: |
          echo "::group::list data/"
          ls -la data || true
          echo "::endgroup::"
          echo "::group::head of csv"
          head -n 2 data/*.csv || true
          echo "::endgroup::"

      # CSV → data/spotify.json（失敗しても空JSONを出す実装）
      - name: Build spotify.json from CSV
        run: python scripts/spotify_ingest.py

      # Pages へ成果物をアップロード
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
